"""Data quality and enforcement-visibility bias audit routines."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd

from curbflow.data.clean import preprocess_violations
from curbflow.data.schema import AUDIT_ONLY_NULLABLE_COLUMNS, CLEAN_PARQUET_PATH, RAW_CSV_PATH
from curbflow.data.time_utils import add_created_datetime_parts
from curbflow.features.novel_features import compute_patrol_myopia_table


REPORTS_DIR = Path("artifacts/reports")
PROCESSED_DIR = Path("data/processed")
DATA_QUALITY_REPORT_PATH = REPORTS_DIR / "data_quality_report.md"
BIAS_AUDIT_REPORT_PATH = REPORTS_DIR / "bias_audit_report.md"
EDA_SUMMARY_PATH = REPORTS_DIR / "eda_summary.json"
COVERAGE_AUDIT_PATH = PROCESSED_DIR / "coverage_audit.parquet"

MORNING_START_MINUTE = 7 * 60 + 30
MORNING_END_MINUTE = 15 * 60 + 30
EVENING_START_MINUTE = 15 * 60 + 30
EVENING_END_MINUTE = 20 * 60 + 30


@dataclass(frozen=True)
class AuditOutputPaths:
    """Output paths generated by the data audit stage."""

    data_quality_report: Path = DATA_QUALITY_REPORT_PATH
    bias_audit_report: Path = BIAS_AUDIT_REPORT_PATH
    eda_summary: Path = EDA_SUMMARY_PATH
    coverage_audit: Path = COVERAGE_AUDIT_PATH


def _as_jsonable(value: Any) -> Any:
    """Convert pandas/numpy values into JSON-safe Python objects."""

    if pd.isna(value):
        return None
    if hasattr(value, "item"):
        return value.item()
    return value


def _value_counts(series: pd.Series, limit: int = 100) -> dict[str, int]:
    """Return normalized value counts with explicit unknown labels."""

    counts = series.fillna("unknown").astype(str).value_counts(dropna=False).head(limit)
    return {str(key): int(value) for key, value in counts.items()}


def _minute_of_day(series: pd.Series) -> pd.Series:
    return series.dt.hour * 60 + series.dt.minute


def _count_between_minutes(series: pd.Series, start_minute: int, end_minute: int) -> int:
    minutes = _minute_of_day(series.dropna())
    return int(((minutes >= start_minute) & (minutes < end_minute)).sum())


def _ensure_created_datetime_ist(frame: pd.DataFrame) -> pd.DataFrame:
    if "created_datetime_ist" in frame.columns:
        result = frame.copy()
        result["created_datetime_ist"] = pd.to_datetime(
            result["created_datetime_ist"],
            utc=True,
            errors="coerce",
        ).dt.tz_convert("Asia/Kolkata")
        return result
    return add_created_datetime_parts(frame)


def _scita_rate(frame: pd.DataFrame) -> float | None:
    if "data_sent_to_scita" not in frame.columns:
        return None
    series = frame["data_sent_to_scita"]
    if series.dtype != "boolean" and series.dtype != bool:
        lowered = series.fillna("").astype(str).str.strip().str.lower()
        series = lowered.map({"true": True, "t": True, "yes": True, "y": True, "1": True, "false": False, "f": False, "no": False, "n": False, "0": False}).astype("boolean")
    known = series.dropna()
    if known.empty:
        return None
    return float(known.mean())


def _patrol_myopia_summary(frame: pd.DataFrame) -> dict[str, Any]:
    """Summarize patrol myopia when station, zone, and time fields are available."""

    required = {"police_station", "zone_id", "created_datetime_ist"}
    if not required.issubset(frame.columns):
        return {
            "available": False,
            "note": "Patrol myopia requires zone_id and is populated after zone assignment.",
        }
    table = compute_patrol_myopia_table(frame)
    if table.empty:
        return {
            "available": False,
            "note": "Patrol myopia could not be computed because no station records were available.",
        }
    top_station = table.iloc[0]
    return {
        "available": True,
        "station_count": int(len(table)),
        "mean_patrol_myopia_index": float(table["patrol_myopia_index"].mean()),
        "max_patrol_myopia_index": float(table["patrol_myopia_index"].max()),
        "high_myopia_station_count": int((table["patrol_myopia_level"] == "High").sum()),
        "top_station": {
            "police_station": str(top_station["police_station"]),
            "patrol_myopia_index": float(top_station["patrol_myopia_index"]),
            "patrol_myopia_level": str(top_station["patrol_myopia_level"]),
            "top_10_zone_share": float(top_station["top_10_zone_share"]),
            "morning_bias": float(top_station["morning_bias"]),
            "zone_coverage_entropy": float(top_station["zone_coverage_entropy"]),
        },
    }


def build_audit_summary(frame: pd.DataFrame) -> dict[str, Any]:
    """Compute data quality, EDA, and enforcement visibility audit metrics."""

    audited = _ensure_created_datetime_ist(frame)
    total_rows = int(len(audited))
    total_columns = int(len(audited.columns))
    created_ist = audited["created_datetime_ist"]
    morning_count = _count_between_minutes(created_ist, MORNING_START_MINUTE, MORNING_END_MINUTE)
    evening_count = _count_between_minutes(created_ist, EVENING_START_MINUTE, EVENING_END_MINUTE)
    validation = audited.get("validation_status", pd.Series(["unknown"] * total_rows)).fillna("unknown").astype(str)
    validation_full = validation.value_counts(dropna=False)
    validation_non_unknown = validation[validation.str.lower().ne("unknown")].value_counts(dropna=False)

    summary: dict[str, Any] = {
        "total_rows": total_rows,
        "total_columns": total_columns,
        "actual_date_range": {
            "start": created_ist.min().isoformat() if created_ist.notna().any() else None,
            "end": created_ist.max().isoformat() if created_ist.notna().any() else None,
        },
        "null_percentage_by_column": {
            column: round(float(audited[column].isna().mean() * 100), 4)
            for column in audited.columns
        },
        "fully_null_columns": {
            column: bool(column in audited.columns and audited[column].isna().all())
            for column in AUDIT_ONLY_NULLABLE_COLUMNS
        },
        "hour_of_day_distribution": {
            str(hour): int(count)
            for hour, count in created_ist.dt.hour.value_counts().reindex(range(24), fill_value=0).sort_index().items()
        },
        "morning_count_0730_1530": morning_count,
        "evening_count_1530_2030": evening_count,
        "evening_gap_ratio_morning_over_evening": (
            float(morning_count / evening_count) if evening_count else None
        ),
        "police_station_counts": _value_counts(audited.get("police_station", pd.Series(dtype=object))),
        "junction_counts": _value_counts(audited.get("junction_name", pd.Series(dtype=object))),
        "vehicle_type_counts": _value_counts(audited.get("vehicle_type", pd.Series(dtype=object))),
        "validation_status_breakdown": {
            "including_unknown": {str(key): int(value) for key, value in validation_full.items()},
            "non_unknown_only": {str(key): int(value) for key, value in validation_non_unknown.items()},
        },
        "data_sent_to_scita_rate": _scita_rate(audited),
        "device_user_counts": {
            "device_id_unique": int(audited["device_id"].nunique(dropna=True)) if "device_id" in audited.columns else None,
            "device_id_non_null_rows": int(audited["device_id"].notna().sum()) if "device_id" in audited.columns else None,
            "created_by_id_unique": int(audited["created_by_id"].nunique(dropna=True)) if "created_by_id" in audited.columns else None,
            "created_by_id_non_null_rows": int(audited["created_by_id"].notna().sum()) if "created_by_id" in audited.columns else None,
        },
        "top_zone_concentration": {
            "available": False,
            "top_10_zone_share": None,
            "note": "Top-zone concentration requires zoning artifacts and will be populated after zone assignment.",
        },
        "patrol_myopia": _patrol_myopia_summary(audited),
        "interpretation_warnings": [
            "This dataset is an enforcement visibility dataset, not a complete record of all illegal parking.",
            "No challan should not be interpreted as no illegal parking.",
            "Evening windows are evidence-poor and should be handled as blind-spot audit windows.",
        ],
    }
    return summary


def write_data_quality_report(summary: dict[str, Any], path: Path = DATA_QUALITY_REPORT_PATH) -> None:
    """Write a markdown data quality report."""

    path.parent.mkdir(parents=True, exist_ok=True)
    full_null = summary["fully_null_columns"]
    lines = [
        "# CurbFlow AI Data Quality Report",
        "",
        "This dataset is an enforcement visibility dataset, not a complete record of all illegal parking.",
        "No challan should not be interpreted as no illegal parking.",
        "Evening windows are evidence-poor and should be handled as blind-spot audit windows.",
        "",
        "## Summary",
        "",
        f"- Total rows: {summary['total_rows']:,}",
        f"- Total columns: {summary['total_columns']:,}",
        f"- Date range IST: {summary['actual_date_range']['start']} to {summary['actual_date_range']['end']}",
        f"- Morning records, 07:30-15:30 IST: {summary['morning_count_0730_1530']:,}",
        f"- Evening records, 15:30-20:30 IST: {summary['evening_count_1530_2030']:,}",
        f"- Evening gap ratio, morning/evening: {summary['evening_gap_ratio_morning_over_evening']}",
        "",
        "## Fully Null Audit Columns",
        "",
    ]
    lines.extend(f"- `{column}`: {is_null}" for column, is_null in full_null.items())
    lines.extend(
        [
            "",
            "## Null Percentage By Column",
            "",
            "| Column | Null % |",
            "|---|---:|",
        ]
    )
    lines.extend(
        f"| `{column}` | {percent:.4f} |"
        for column, percent in summary["null_percentage_by_column"].items()
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_bias_audit_report(summary: dict[str, Any], path: Path = BIAS_AUDIT_REPORT_PATH) -> None:
    """Write a markdown bias and visibility audit report."""

    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# CurbFlow AI Bias Audit Report",
        "",
        "This dataset is an enforcement visibility dataset, not a complete record of all illegal parking.",
        "No challan should not be interpreted as no illegal parking.",
        "Evening windows are evidence-poor and should be handled as blind-spot audit windows.",
        "",
        "## Operational Window Evidence",
        "",
        f"- Morning records, 07:30-15:30 IST: {summary['morning_count_0730_1530']:,}",
        f"- Evening records, 15:30-20:30 IST: {summary['evening_count_1530_2030']:,}",
        f"- Evening gap ratio, morning/evening: {summary['evening_gap_ratio_morning_over_evening']}",
        "",
        "## Validation Status",
        "",
        "### Including Unknown",
        "",
    ]
    lines.extend(
        f"- {status}: {count:,}"
        for status, count in summary["validation_status_breakdown"]["including_unknown"].items()
    )
    lines.extend(["", "### Non-Unknown Only", ""])
    lines.extend(
        f"- {status}: {count:,}"
        for status, count in summary["validation_status_breakdown"]["non_unknown_only"].items()
    )
    lines.extend(
        [
            "",
            "## Top-Zone Concentration",
            "",
            summary["top_zone_concentration"]["note"],
            "",
            "## Patrol Myopia",
            "",
        ]
    )
    patrol_myopia = summary.get("patrol_myopia", {"available": False})
    if patrol_myopia.get("available"):
        top_station = patrol_myopia["top_station"]
        lines.extend(
            [
                f"- Stations scored: {patrol_myopia['station_count']:,}",
                f"- High-myopia stations: {patrol_myopia['high_myopia_station_count']:,}",
                f"- Mean Patrol Myopia Index: {patrol_myopia['mean_patrol_myopia_index']:.4f}",
                f"- Max Patrol Myopia Index: {patrol_myopia['max_patrol_myopia_index']:.4f}",
                f"- Highest station: {top_station['police_station']} ({top_station['patrol_myopia_level']}, {top_station['patrol_myopia_index']:.4f})",
            ]
        )
    else:
        lines.append(patrol_myopia.get("note", "Patrol myopia is unavailable."))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_eda_summary(summary: dict[str, Any], path: Path = EDA_SUMMARY_PATH) -> None:
    """Write the JSON EDA summary."""

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(summary, indent=2, default=_as_jsonable), encoding="utf-8")


def write_coverage_audit_placeholder(
    summary: dict[str, Any],
    path: Path = COVERAGE_AUDIT_PATH,
) -> None:
    """Write a placeholder coverage audit artifact before zoning is available."""

    path.parent.mkdir(parents=True, exist_ok=True)
    frame = pd.DataFrame(
        [
            {
                "total_rows": summary["total_rows"],
                "morning_count_0730_1530": summary["morning_count_0730_1530"],
                "evening_count_1530_2030": summary["evening_count_1530_2030"],
                "evening_gap_ratio_morning_over_evening": summary[
                    "evening_gap_ratio_morning_over_evening"
                ],
                "data_sent_to_scita_rate": summary["data_sent_to_scita_rate"],
                "top_zone_concentration_available": False,
                "top_zone_concentration_note": summary["top_zone_concentration"]["note"],
            }
        ]
    )
    frame.to_parquet(path, index=False)


def run_data_audit(
    clean_parquet_path: str | Path = CLEAN_PARQUET_PATH,
    raw_csv_path: str | Path = RAW_CSV_PATH,
    output_paths: AuditOutputPaths = AuditOutputPaths(),
) -> dict[str, Any]:
    """Load cleaned data, compute audits, and write all audit artifacts."""

    clean_path = Path(clean_parquet_path)
    if clean_path.exists():
        frame = pd.read_parquet(clean_path)
    else:
        frame = preprocess_violations(raw_csv_path, clean_path)

    summary = build_audit_summary(frame)
    write_data_quality_report(summary, output_paths.data_quality_report)
    write_bias_audit_report(summary, output_paths.bias_audit_report)
    write_eda_summary(summary, output_paths.eda_summary)
    write_coverage_audit_placeholder(summary, output_paths.coverage_audit)
    return summary
